# ============================================================
# Reproduce the complete analysis workflow
# ============================================================

# This script reproduces the main analysis workflow described
# in the README, from pedigree preparation through the combined
# LOD–Jaccard analyses.
#
# Figures and manuscript tables are generated by separate scripts:
#   examples/reproduce_manuscript_figures.R
#   examples/reproduce_manuscript_tables.R
# ============================================================


# ------------------------------------------------------------
# 0. Setup
# ------------------------------------------------------------

# source("setup.R")


# ------------------------------------------------------------
# 1. Pedigree preparation
# ------------------------------------------------------------

ped <- create_pedigree_subsets(data)

varieties_both_parents <- ped$biparental_subset
varieties_any_parent  <- ped$uniparental_subset


# Check expected subset sizes
stopifnot(
  nrow(varieties_both_parents) == 266,
  nrow(varieties_any_parent) == 572
)


# ------------------------------------------------------------
# 2. Jaccard similarity
# ------------------------------------------------------------

J <- compute_jaccard_matrix_cpp(bin_matrix)


# ------------------------------------------------------------
# 2.1. Jaccard parent-retrieval analysis
# ------------------------------------------------------------

top_values <- c(1, 5, 10, 20)

jaccard_both <- list()
jaccard_any <- list()

for (k in top_values) {

  jaccard_both[[paste0("Top", k)]] <-
    analyze_parentage_jaccard(
      data,
      J,
      varieties_both_parents,
      top_k = k
    )

  jaccard_any[[paste0("Top", k)]] <-
    analyze_parentage_jaccard(
      data,
      J,
      varieties_any_parent,
      top_k = k
    )
}


# ------------------------------------------------------------
# 2.2. Jaccard structural analysis
# ------------------------------------------------------------

jaccard_struct_both <-
  generate_jaccard_relationship_scores(
    data,
    J,
    varieties_both_parents
  )

jaccard_struct_any <-
  generate_jaccard_relationship_scores(
    data,
    J,
    varieties_any_parent
  )


results_both <-
  analyze_jaccard_relationships(
    jaccard_struct_both
  )

results_any <-
  analyze_jaccard_relationships(
    jaccard_struct_any
  )


# Dunn-test effect sizes

effect_both <-
  calculate_dunn_effect_size(
    results_both$dunn,
    nrow(jaccard_struct_both)
  )

effect_any <-
  calculate_dunn_effect_size(
    results_any$dunn,
    nrow(jaccard_struct_any)
  )


# ------------------------------------------------------------
# 3. LOD analysis
# ------------------------------------------------------------

L <- compute_lod_matrix_cpp(bin_matrix)


# ------------------------------------------------------------
# 3.1. LOD parent-retrieval analysis
# ------------------------------------------------------------

lod_both <- list()
lod_any <- list()

for (k in top_values) {

  lod_both[[paste0("Top", k)]] <-
    analyze_parentage_lod(
      data,
      L,
      varieties_both_parents,
      top_n = k
    )

  lod_any[[paste0("Top", k)]] <-
    analyze_parentage_lod(
      data,
      L,
      varieties_any_parent,
      top_n = k
    )
}


# ------------------------------------------------------------
# 4. Combined LOD–Jaccard analysis
# ------------------------------------------------------------

# 4.1. Top-10 LOD + Top-10 Jaccard

combined_both <-
  analyze_parentage_combined(
    jaccard_both$Top10,
    lod_both$Top10,
    jaccard_selection = "top",
    top_k = 10
  )

combined_any <-
  analyze_parentage_combined(
    jaccard_any$Top10,
    lod_any$Top10,
    jaccard_selection = "top",
    top_k = 10
  )


# 4.2. Top-10 LOD + Jaccard similarity interval

combined_both_iqr <-
  analyze_parentage_combined(
    jaccard_both$Top10,
    lod_both$Top10,
    jaccard_selection = "range",
    top_k = 10,
    jaccard_min = 0.57,
    jaccard_max = 1
  )

combined_any_iqr <-
  analyze_parentage_combined(
    jaccard_any$Top10,
    lod_any$Top10,
    jaccard_selection = "range",
    top_k = 10,
    jaccard_min = 0.57,
    jaccard_max = 1
  )


# ------------------------------------------------------------
# Workflow completed
# ------------------------------------------------------------

message("Complete analysis workflow successfully reproduced.")